apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopslab-deploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: devopslab-pod
    spec:
      containers:
      - name: devopslab-pod
        image: ddrsdiego/devopslab:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: devopslab-pod