apiVersion: v1
kind: Service
metadata:
  name: devopslab-service
spec:
  type: ClusterIP
  selector:
    app: devopslab-deploy
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
