apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
      tier: db
  template:
    metadata:
      name: redis
      labels:
        app: redis
        tier: db
    spec:
      containers:
      - name: redis
        image: redis:bullseye
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 6379
