apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
    tier: db
spec:
  containers:
  - name: redis
    image: redis:bullseye
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 6379