apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP
  ports:
  - port: 7000
    targetPort: 80
    protocol: TCP
  selector:
    name: nginx 
    app: nginx-pod
    tier: proxy