---
apiVersion: v1
kind: Service
metadata:
  name: devopslab-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    name: devopslab-pod
    app: devopslab
